### ISSUE TITLE
add multi-channel contract for merchant

### ISSUE THREAD

**Issue by jakinyele** [boltlabs-inc/tezos-contract#36] opened 2021-08-10 14:56 UTC
A multi-channel contract deployed per merchant will shift origination/storage cost from the customer to the merchant. Would also simplify the UX for customers in that they only need the deployed contract address to verify details before opening the zkChannel.

**Comment by DariusParvin** [comment] 2021-08-30 18:41
this issue is a duplicate of #3

**Closed by DariusParvin** 2021-08-30 18:41 UTC
